/*
Copyright 2026 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package manager

import (
	"context"
	"regexp"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/spf13/afero"

	devv1alpha1 "github.com/crossplane/cli/v2/apis/dev/v1alpha1"
	"github.com/crossplane/cli/v2/internal/schemas/generator"
	"github.com/crossplane/cli/v2/internal/schemas/runner"
)

var rustModDeclRE = regexp.MustCompile(`(?m)^(?:pub )?mod (\w+);`)

// TestGenerateRustModuleTreeAcrossSources covers the reason the Rust generator
// leaves its module declarations to the manager: every source's models are
// copied into one crate, and a generator run only ever sees its own source. The
// declarations have to describe the merged crate, or the second source to
// generate leaves a crate that doesn't compile.
func TestGenerateRustModuleTreeAcrossSources(t *testing.T) {
	t.Parallel()

	cases := map[string]struct {
		reason string
		args   struct {
			// sources is the files the generator writes for each source, in
			// the order the sources are generated.
			sources [][]string
		}
		want struct {
			// modules is the modules each file declares.
			modules map[string][]string
		}
	}{
		"DependencyExtendsTheProjectsModules": {
			reason: "The declarations describe the merged crate, not only the source generated last.",
			args: struct{ sources [][]string }{sources: [][]string{
				// The project's own XRDs.
				{
					"models/src/com/example/v1/widget.rs",
					"models/src/io/k8s/apimachinery/pkg/apis/meta/v1/objectmeta.rs",
				},
				// A dependency that adds a kind to a module the project already
				// generated, plus a module of its own.
				{
					"models/src/com/example/v1/gadget.rs",
					"models/src/io/upbound/aws/s3/v1beta2/bucket.rs",
					"models/src/io/k8s/apimachinery/pkg/apis/meta/v1/objectmeta.rs",
				},
			}},
			want: struct{ modules map[string][]string }{modules: map[string][]string{
				"rust/src/lib.rs":                                      {"com", "io"},
				"rust/src/com/example/v1/mod.rs":                       {"gadget", "widget"},
				"rust/src/io/mod.rs":                                   {"k8s", "upbound"},
				"rust/src/io/k8s/apimachinery/pkg/apis/meta/v1/mod.rs": {"objectmeta"},
				"rust/src/io/upbound/aws/s3/v1beta2/mod.rs":            {"bucket"},
			}},
		},
	}

	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			testFS := afero.NewMemMapFs()
			for i, files := range tc.args.sources {
				m := New(testFS, []generator.Interface{&rustMockGenerator{files: files}}, nil)
				if _, err := m.Generate(t.Context(), &mockSource{id: "source", version: "v1.0.0"}); err != nil {
					t.Fatalf("\n%s\nGenerate(...) for source %d: %v", tc.reason, i, err)
				}
			}

			for path, want := range tc.want.modules {
				contents, err := afero.ReadFile(testFS, path)
				if err != nil {
					t.Errorf("\n%s\nreading %s: %v", tc.reason, path, err)
					continue
				}
				decls := rustModDeclRE.FindAllStringSubmatch(string(contents), -1)
				got := make([]string, 0, len(decls))
				for _, m := range decls {
					got = append(got, m[1])
				}
				if diff := cmp.Diff(want, got); diff != "" {
					t.Errorf("\n%s\n%s: -want modules, +got modules:\n%s", tc.reason, path, diff)
				}
			}
		})
	}
}

// rustMockGenerator writes the given files, as the Rust generator does for the
// schemas of one source.
type rustMockGenerator struct {
	files []string
}

func (g *rustMockGenerator) Language() string {
	return devv1alpha1.SchemaLanguageRust
}

func (g *rustMockGenerator) GenerateFromCRD(_ context.Context, _ afero.Fs, _ runner.SchemaRunner) (afero.Fs, error) {
	fs := afero.NewMemMapFs()
	for _, path := range g.files {
		if err := afero.WriteFile(fs, path, []byte("// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.\n"), 0o600); err != nil {
			return nil, err
		}
	}
	return fs, nil
}

func (g *rustMockGenerator) GenerateFromOpenAPI(_ context.Context, _ afero.Fs, _ runner.SchemaRunner) (afero.Fs, error) {
	return nil, nil
}
