/*
Copyright 2026 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package generator

import (
	"context"
	"maps"
	"path"
	"slices"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/spf13/afero"
	"k8s.io/kube-openapi/pkg/validation/spec"

	"github.com/crossplane/crossplane-runtime/v2/pkg/errors"

	devv1alpha1 "github.com/crossplane/cli/v2/apis/dev/v1alpha1"
	"github.com/crossplane/cli/v2/internal/schemas/runner"
)

const (
	// rustModelsDir is the directory generators write their output to, which
	// the schema manager strips when it copies them into the project.
	rustModelsDir = "models"

	// rustSrcDir is the crate's source directory, relative to the crate root.
	rustSrcDir = "src"

	// rustGeneratedHeader marks every file we emit. It matches the convention
	// Go tooling recognizes, which several editors and linters reuse.
	rustGeneratedHeader = "// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT."

	// rustMaxDepth caps how deep we walk into inline objects. Structural
	// schemas are finite trees, so this only guards against pathological input
	// taking the whole CLI down with a stack overflow. rustc gives up on types
	// nested about this deep anyway; the limit is here so that the generator's
	// own behavior is explicit rather than left to the size of the Go stack.
	rustMaxDepth = 64

	// rustSharedPackage prefixes the component schemas that both generation
	// flows emit, see rustPrepareSchemas.
	rustSharedPackage = "io.k8s.apimachinery."

	// rustAdditionalProperties is the JSON-side name of the field that keeps
	// the properties a schema allows without naming them.
	rustAdditionalProperties = "additionalProperties"

	// rustPreserveUnknownFields marks an object whose unknown fields the API
	// server keeps.
	rustPreserveUnknownFields = "x-kubernetes-preserve-unknown-fields"
)

// rustCargoToml is the crate manifest, up to the features table that
// rustRenderCargoToml derives from the crate's modules.
const rustCargoToml = `# Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.
[package]
name = "crossplane-models"
version = "0.0.1"
edition = "2024"
publish = false
description = "Rust models generated by the Crossplane CLI from a project's XRDs and dependencies."

[lib]
path = "src/lib.rs"
# Schema descriptions become doc comments verbatim, and some of them contain
# indented or fenced blocks that rustdoc would otherwise collect as doctests
# and try to compile as Rust.
doctest = false

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
`

// rustCrateAttributes are the inner attributes of the crate root. Generated
// code is not held to the same lints as hand-written code, and the descriptions
// we turn into doc comments are arbitrary prose from a CRD.
const rustCrateAttributes = `#![allow(clippy::all)]
#![allow(non_camel_case_types, non_snake_case)]
#![allow(rustdoc::bare_urls, rustdoc::broken_intra_doc_links, rustdoc::invalid_html_tags)]
#![doc = "Rust models generated by the Crossplane CLI from a project's XRDs and dependencies."]
`

type rustGenerator struct{}

func (rustGenerator) Language() string {
	return devv1alpha1.SchemaLanguageRust
}

// GenerateFromCRD generates Rust models for the XRDs and CRDs in the given
// filesystem.
func (rustGenerator) GenerateFromCRD(_ context.Context, fromFS afero.Fs, _ runner.SchemaRunner) (afero.Fs, error) {
	openAPIs, err := goCollectOpenAPIs(fromFS)
	if err != nil {
		return nil, err
	}

	if len(openAPIs) == 0 {
		return nil, nil
	}

	// Every CRD's OpenAPI document carries its own copy of the shared
	// Kubernetes schemas it references (ObjectMeta and friends). Merging them
	// into one set means we generate one file per type, whichever document it
	// came from, and the emitter can resolve every $ref by name.
	schemas := make(map[string]*spec.Schema)
	for _, oapi := range openAPIs {
		if oapi.spec.Components == nil {
			continue
		}
		goRemoveValidationOnlyCombinators(oapi.spec)
		maps.Copy(schemas, oapi.spec.Components.Schemas)
	}

	return rustGenerateModels(schemas)
}

// GenerateFromOpenAPI generates Rust models for the OpenAPI v3 documents in the
// given filesystem.
func (rustGenerator) GenerateFromOpenAPI(_ context.Context, fromFS afero.Fs, _ runner.SchemaRunner) (afero.Fs, error) {
	openAPIs, err := collectOpenAPISpecs(fromFS)
	if err != nil {
		return nil, err
	}

	if len(openAPIs) == 0 {
		return nil, nil
	}

	schemas := make(map[string]*spec.Schema)
	for _, oapi := range openAPIs {
		// Unlike CRD schemas, which get their apiVersion and kind defaults
		// from crd.ToOpenAPI, schemas from a live API server carry a
		// group-version-kind extension we have to turn into defaults
		// ourselves. They are what marks a type as a root, see rustRootOf.
		goAddDefaults(oapi)
		goRemoveValidationOnlyCombinators(oapi)
		maps.Copy(schemas, oapi.Components.Schemas)
	}

	return rustGenerateModels(schemas)
}

// rustGenerateModels writes the crossplane-models crate for the given component
// schemas into the models directory of a new filesystem.
func rustGenerateModels(schemas map[string]*spec.Schema) (afero.Fs, error) {
	// A crate with no types would still need a lib.rs to be a crate at all, so
	// generate nothing rather than something broken.
	if len(schemas) == 0 {
		return nil, nil
	}

	rustPrepareSchemas(schemas)
	if len(schemas) == 0 {
		return nil, nil
	}

	schemaFS := afero.NewMemMapFs()
	crateFS := afero.NewBasePathFs(schemaFS, rustModelsDir)

	names := slices.Sorted(maps.Keys(schemas))
	boxed := rustDetectCycles(schemas)

	// Directories are named after schema name segments and files after type
	// names, so a kind named like one of its own sub-packages would give its
	// module two children of the same name. Collect the directories up front to
	// keep file names clear of them.
	dirs := make(map[string]bool, len(names))
	for _, name := range names {
		module, _ := rustSplitSchemaName(name)
		for i := range module {
			dirs[rustModuleDir(module[:i+1])] = true
		}
	}

	written := make(map[string]string, len(names))
	for _, group := range rustGroupSchemas(schemas) {
		if err := crateFS.MkdirAll(group.dir, 0o755); err != nil {
			return nil, errors.Wrapf(err, "failed to create directory %q", group.dir)
		}

		file := rustFilePath(group.dir, group.stem, dirs, written)
		written[file] = group.primary

		if err := afero.WriteFile(crateFS, file, rustEmitFile(group, schemas, boxed), 0o644); err != nil {
			return nil, errors.Wrapf(err, "failed to write models for schema %q", group.primary)
		}
	}

	if err := BuildRustModuleTree(crateFS); err != nil {
		return nil, err
	}

	return schemaFS, nil
}

// rustPrepareSchemas makes the component schemas safe to emit.
//
// A schema without a usable type name is dropped, as the Go generator does. A
// CRD that leaves spec.names.listKind to the API server's defaulting has one:
// its list schema is named after the group and version alone.
//
// The shared Kubernetes types (ObjectMeta, Status, DeleteOptions, ...) are
// written by every source, into the same files: the CRD flow emits the ones a
// CRD refers to, and the OpenAPI flow emits all of them. The schema manager
// copies each source's output over the last and never deletes, so both flows
// have to produce those files identically, whichever runs last. They would not:
// goAddDefaults gives Status and DeleteOptions an apiVersion and kind in the
// OpenAPI flow only, which would make them resources there, with consts, a
// Default impl and the types named after them grouped into their file. Nobody
// composes those types, so they are plain structs in both flows instead.
func rustPrepareSchemas(schemas map[string]*spec.Schema) {
	for name, s := range schemas {
		if _, typ := rustSplitSchemaName(name); typ == "" {
			delete(schemas, name)
			continue
		}
		if s == nil || !strings.HasPrefix(name, rustSharedPackage) {
			continue
		}
		for _, field := range []string{"apiVersion", "kind"} {
			prop, ok := s.Properties[field]
			if !ok {
				continue
			}
			prop.Default = nil
			prop.Enum = nil
			s.Properties[field] = prop
		}
	}
}

// rustModuleDir returns the directory holding a module path's types.
func rustModuleDir(module []string) string {
	return path.Join(append([]string{rustSrcDir}, module...)...)
}

// rustFileGroup is the set of component schemas emitted into one file, named
// after the kind they belong to.
type rustFileGroup struct {
	dir     string
	stem    string
	primary string   // the schema the file is named after
	schemas []string // every schema in the file, sorted, primary first
}

// rustGroupSchemas decides which file each component schema is emitted into.
// Everything that belongs to a kind is emitted with it, so a CronJob's spec,
// status and list types are in cronjob.rs rather than three files of their own:
//
//   - a kind gets its own file;
//   - a <Kind>List kind is emitted with its <Kind>, being a wrapper around it
//     rather than a resource anyone composes;
//   - anything else joins the kind whose name it starts with, longest name
//     first, which is how the Kubernetes API names a kind's helper types
//     (PodSpec, PodTemplateSpec, DeploymentStrategy);
//   - a schema named after no kind keeps its own file (ObjectMeta, Container,
//     LabelSelector).
//
// Grouping depends on which kinds a source knows about, so it is only safe for
// files a single source writes. The shared Kubernetes types are written by
// every source; rustPrepareSchemas makes sure none of them is a kind, which
// leaves each of them in a file of its own.
//
// The result is sorted, so the emitted crate does not depend on map order.
func rustGroupSchemas(schemas map[string]*spec.Schema) []rustFileGroup {
	type schemaInfo struct{ name, typ string }

	byDir := make(map[string][]schemaInfo)
	kinds := make(map[string]map[string]bool)
	for _, name := range slices.Sorted(maps.Keys(schemas)) {
		module, typ := rustSplitSchemaName(name)
		dir := rustModuleDir(module)

		byDir[dir] = append(byDir[dir], schemaInfo{name: name, typ: typ})
		if rustRootOf(schemas[name]) != nil {
			if kinds[dir] == nil {
				kinds[dir] = make(map[string]bool)
			}
			kinds[dir][typ] = true
		}
	}

	groups := make([]rustFileGroup, 0, len(schemas))
	for _, dir := range slices.Sorted(maps.Keys(byDir)) {
		owners := make(map[string][]string)
		primaries := make(map[string]string)

		for _, s := range byDir[dir] {
			owner := rustFileOwner(s.typ, kinds[dir])
			owners[owner] = append(owners[owner], s.name)
			if s.typ == owner {
				primaries[owner] = s.name
			}
		}

		for _, owner := range slices.Sorted(maps.Keys(owners)) {
			names := owners[owner]
			slices.Sort(names)

			// The kind leads its file. A file grouped under a kind whose own
			// schema we never saw (a dangling reference) is named after it
			// anyway, and its first schema leads.
			primary := primaries[owner]
			if primary == "" {
				primary = names[0]
			} else if i := slices.Index(names, primary); i > 0 {
				names = slices.Concat([]string{primary}, names[:i], names[i+1:])
			}

			groups = append(groups, rustFileGroup{
				dir:     dir,
				stem:    rustFileStem(owner),
				primary: primary,
				schemas: names,
			})
		}
	}

	return groups
}

// rustFileOwner returns the type whose file typ is emitted into, given the
// kinds its module defines. See rustGroupSchemas for the rules.
func rustFileOwner(typ string, kinds map[string]bool) string {
	if kinds[typ] {
		if base, ok := strings.CutSuffix(typ, "List"); ok && kinds[base] {
			return base
		}
		return typ
	}

	owner := ""
	for kind := range kinds {
		if len(kind) <= len(owner) || !rustNamePrefix(typ, kind) {
			continue
		}
		owner = kind
	}
	if owner == "" {
		return typ
	}

	// The owning kind may itself be emitted with another kind.
	return rustFileOwner(owner, kinds)
}

// rustNamePrefix reports whether name starts with prefix at a word boundary,
// so Pod owns PodSpec but not Podium.
func rustNamePrefix(name, prefix string) bool {
	rest, ok := strings.CutPrefix(name, prefix)
	if !ok || rest == "" {
		return false
	}
	r, _ := utf8.DecodeRuneInString(rest)
	return unicode.IsUpper(r)
}

// rustFilePath returns the file to write a type to, keeping clear of directory
// names and of files already written for a different schema.
func rustFilePath(dir, stem string, dirs map[string]bool, written map[string]string) string {
	base := stem
	for n := 2; ; n++ {
		file := path.Join(dir, stem+".rs")
		if !dirs[path.Join(dir, stem)] && written[file] == "" {
			return file
		}
		stem = base + "_" + strconv.Itoa(n)
	}
}

// rustTypeKind is the kind of Rust item generated for a schema.
type rustTypeKind int

const (
	// rustStruct is an object schema with properties.
	rustStruct rustTypeKind = iota
	// rustAlias is a scalar or unstructured schema, e.g. Time or RawExtension.
	rustAlias
	// rustUntagged is a schema that is a choice of scalars, e.g. Quantity.
	rustUntagged
)

// rustType is one item in a generated file.
type rustType struct {
	name string
	doc  string
	kind rustTypeKind

	fields   []rustField   // rustStruct, sorted by JSON name
	alias    string        // rustAlias
	variants []rustVariant // rustUntagged
	root     *rustRoot     // set for types that are a Kubernetes resource
}

type rustField struct {
	name     string // Rust identifier
	jsonName string
	doc      string
	typ      string // already wrapped in Option<...>, or a map for a flattened field

	// flatten marks the field that keeps the properties a schema allows
	// without naming them. It is a map serde flattens into the struct.
	flatten bool
}

type rustVariant struct {
	name string
	typ  string
}

// rustRoot holds the apiVersion and kind a resource's Default impl pre-fills.
type rustRoot struct {
	apiVersion string
	kind       string
}

// rustFile accumulates the types emitted into a single file: the type generated
// for its component schema, plus one struct per inline object nested in it.
type rustFile struct {
	schema string                  // the component schema being emitted
	all    map[string]*spec.Schema // every known schema, for $ref resolution
	boxed  map[rustEdge]bool       // references that must be boxed, see rustDetectCycles

	names map[string]bool
	types []rustType
}

// rustEmitFile renders a group of component schemas, and every inline object
// nested in them, into the contents of one Rust file.
func rustEmitFile(group rustFileGroup, all map[string]*spec.Schema, boxed map[rustEdge]bool) []byte {
	f := &rustFile{all: all, boxed: boxed, names: make(map[string]bool)}

	// Reserve the component schemas' own names before emitting anything. Other
	// files refer to them by an absolute crate path derived from the schema
	// name, so a component type must always get the name that path expects; an
	// inline object that would collide with one gives way instead.
	types := make([]string, len(group.schemas))
	for i, name := range group.schemas {
		_, typ := rustSplitSchemaName(name)
		types[i] = f.reserve(typ)
	}

	for i, name := range group.schemas {
		f.schema = name
		f.addNamedType(types[i], all[name])
	}

	slices.SortFunc(f.types, func(a, b rustType) int { return strings.Compare(a.name, b.name) })

	// The kind the file is named after leads it; everything else, including the
	// inline structs, follows in name order.
	if i := slices.IndexFunc(f.types, func(t rustType) bool { return t.name == types[0] }); i > 0 {
		lead := f.types[i]
		f.types = slices.Concat([]rustType{lead}, f.types[:i], f.types[i+1:])
	}

	return rustRenderFile(f.types)
}

// reserve claims a type name for this file. Two inline objects at different
// property paths can produce the same name (a.bC and aB.c both give ABC), so
// the second one to ask gets a numeric suffix. The name is derived from the
// schema, and schemas are walked in sorted order, so which one that is stays
// stable across runs.
func (f *rustFile) reserve(name string) string {
	if !f.names[name] {
		f.names[name] = true
		return name
	}
	for n := 2; ; n++ {
		candidate := name + strconv.Itoa(n)
		if !f.names[candidate] {
			f.names[candidate] = true
			return candidate
		}
	}
}

// addNamedType emits the type a component schema is named after. Objects with
// properties become structs; a choice of scalars becomes an untagged enum
// (Quantity, IntOrString); anything else becomes a type alias, which is how
// scalar wrappers (Time) and unstructured types (RawExtension) stay usable.
func (f *rustFile) addNamedType(name string, s *spec.Schema) {
	if s == nil {
		f.types = append(f.types, rustType{name: name, kind: rustAlias, alias: rustValueType})
		return
	}

	switch variants := rustScalarVariants(s); {
	case len(s.Properties) > 0:
		f.types = append(f.types, f.structType(name, s, 0))
	case len(variants) > 0:
		f.types = append(f.types, rustType{
			name:     name,
			doc:      s.Description,
			kind:     rustUntagged,
			variants: variants,
		})
	default:
		f.types = append(f.types, rustType{
			name:  name,
			doc:   s.Description,
			kind:  rustAlias,
			alias: f.typeFor(name, s, 0, false),
		})
	}
}

// structType builds the struct for an object schema. Every field is optional:
// a function sets only the fields it owns, and observed resources are routinely
// partial, which is the same reasoning behind goRemoveRequired.
func (f *rustFile) structType(name string, s *spec.Schema, depth int) rustType {
	t := rustType{name: name, doc: s.Description, kind: rustStruct, root: rustRootOf(s)}

	// Two properties can map to one identifier (mirrorPercent and
	// mirror_percent, proxyURL and proxyUrl). Properties are walked in sorted
	// order, so which one keeps the plain name is stable across runs, and the
	// rename attribute keeps both on the wire under their own names.
	idents := make(map[string]bool, len(s.Properties)+1)

	for _, jsonName := range slices.Sorted(maps.Keys(s.Properties)) {
		prop := s.Properties[jsonName]
		t.fields = append(t.fields, rustField{
			name:     rustReserveIdent(idents, rustFieldIdent(jsonName)),
			jsonName: jsonName,
			doc:      rustFieldDoc(&prop),
			typ:      "Option<" + f.typeFor(rustNestedTypeName(name, jsonName), &prop, depth+1, false) + ">",
		})
	}

	if value := f.additionalPropertiesType(name, s, depth); value != "" {
		t.fields = append(t.fields, rustField{
			name:    rustReserveIdent(idents, rustFieldIdent(rustAdditionalProperties)),
			doc:     "Properties the schema allows without naming them.",
			typ:     rustMapType + "<" + rustStringType + ", " + value + ">",
			flatten: true,
		})
	}

	return t
}

// additionalPropertiesType returns the value type of the properties an object
// with named properties allows beyond those, or "" if it allows none. Without a
// field for them a model would drop them on the way from observed to desired
// state, which for an object the API server keeps unknown fields of is data the
// function never meant to remove.
func (f *rustFile) additionalPropertiesType(name string, s *spec.Schema, depth int) string {
	if ap := s.AdditionalProperties; ap != nil {
		if ap.Schema != nil {
			return f.typeFor(rustNestedTypeName(name, rustAdditionalProperties), ap.Schema, depth+1, true)
		}
		if ap.Allows {
			return rustValueType
		}
	}

	if preserve, ok := s.Extensions.GetBool(rustPreserveUnknownFields); ok && preserve {
		return rustValueType
	}

	return ""
}

// rustReserveIdent claims an identifier in a struct, giving the second field to
// ask for one a numeric suffix.
func rustReserveIdent(taken map[string]bool, ident string) string {
	candidate := ident
	for n := 2; taken[candidate]; n++ {
		candidate = ident + "_" + strconv.Itoa(n)
	}
	taken[candidate] = true
	return candidate
}

// typeFor maps a property schema to the Rust type expression for it, adding a
// struct to the file for every inline object it walks through. nested is the
// name to give the struct if this position turns out to be one. indirect says
// whether the position is already behind a Vec or a BTreeMap, in which case a
// reference does not need boxing to have a finite size.
//
// An unknown or unstructured shape maps to serde_json::Value rather than
// failing: a model that deserializes every observed resource is worth more than
// one that describes some of them perfectly.
func (f *rustFile) typeFor(nested string, s *spec.Schema, depth int, indirect bool) string {
	if s == nil || depth > rustMaxDepth {
		return rustValueType
	}

	// A $ref, or the allOf wrapper CRD and Kubernetes schemas use to attach a
	// description to one.
	if target := rustRefTarget(s.Ref.String()); target != "" {
		return f.refType(target, indirect)
	}
	if len(s.AllOf) == 1 && rustNoOwnStructure(s) {
		return f.typeFor(nested, &s.AllOf[0], depth+1, indirect)
	}

	switch {
	case s.Type.Contains("array"):
		if s.Items == nil || s.Items.Schema == nil {
			return "Vec<" + rustValueType + ">"
		}
		return "Vec<" + f.typeFor(rustItemTypeName(nested), s.Items.Schema, depth+1, true) + ">"

	case len(s.Properties) > 0:
		name := f.reserve(nested)
		t := f.structType(name, s, depth)
		f.types = append(f.types, t)
		return name

	case s.AdditionalProperties != nil && s.AdditionalProperties.Schema != nil:
		// BTreeMap rather than HashMap: its serialization is ordered, which
		// keeps a function's output stable.
		return rustMapType + "<" + rustStringType + ", " + f.typeFor(nested+"Value", s.AdditionalProperties.Schema, depth+1, true) + ">"

	case s.Type.Contains("string"):
		// Including format: byte, date-time and password. Keeping them all
		// strings is what lets the crate depend on serde alone.
		return rustStringType

	case s.Type.Contains("integer"):
		if s.Format == "int32" {
			return "i32"
		}
		return "i64"

	case s.Type.Contains("number"):
		return "f64"

	case s.Type.Contains("boolean"):
		return "bool"
	}

	// Objects without properties (x-kubernetes-preserve-unknown-fields,
	// embedded resources, RawExtension), inline unions such as
	// x-kubernetes-int-or-string, and schemas with no type at all.
	return rustValueType
}

// refType returns the type expression for a reference to another component
// schema. References to schemas we are not generating fall back to
// serde_json::Value, so a partial input still produces a crate that compiles.
func (f *rustFile) refType(target string, indirect bool) string {
	if _, ok := f.all[target]; !ok {
		return rustValueType
	}

	p := rustPathForSchemaName(target)
	if !indirect && f.boxed[rustEdge{from: f.schema, to: target}] {
		return "Box<" + p + ">"
	}

	return p
}

// rustNoOwnStructure reports whether a schema describes nothing itself, which
// is what makes a single-element allOf a transparent wrapper.
func rustNoOwnStructure(s *spec.Schema) bool {
	return len(s.Type) == 0 && len(s.Properties) == 0 && s.Items == nil && s.AdditionalProperties == nil
}

// rustScalarVariants returns the untagged enum variants for a schema that is a
// choice between scalar types, e.g. Quantity (string or number) and IntOrString.
// It returns nil for anything else, including choices involving objects: serde
// resolves untagged variants by trying them in order, which is only predictable
// for scalars.
func rustScalarVariants(s *spec.Schema) []rustVariant {
	variants := s.OneOf
	if len(variants) == 0 {
		variants = s.AnyOf
	}
	if len(variants) < 2 {
		return nil
	}

	out := make([]rustVariant, 0, len(variants))
	seen := make(map[string]bool, len(variants))
	for i := range variants {
		v := rustScalarVariant(&variants[i])
		if v.name == "" {
			return nil
		}
		if seen[v.name] {
			continue
		}
		seen[v.name] = true
		out = append(out, v)
	}

	return out
}

func rustScalarVariant(s *spec.Schema) rustVariant {
	if len(s.Properties) > 0 || s.Ref.String() != "" || len(s.AllOf) > 0 {
		return rustVariant{}
	}

	switch {
	case s.Type.Contains("integer"):
		if s.Format == "int32" {
			return rustVariant{name: "Int", typ: "i32"}
		}
		return rustVariant{name: "Int", typ: "i64"}
	case s.Type.Contains("number"):
		return rustVariant{name: "Number", typ: "f64"}
	case s.Type.Contains("string"):
		return rustVariant{name: rustStringType, typ: rustStringType}
	case s.Type.Contains("boolean"):
		return rustVariant{name: "Bool", typ: "bool"}
	}

	return rustVariant{}
}

// rustRootOf returns the apiVersion and kind of a schema that describes a
// Kubernetes resource, or nil if it does not. Both properties carry a default
// for exactly those schemas: crd.ToOpenAPI sets them for the kind a CRD
// defines, and goAddDefaults derives them from the group-version-kind extension
// of a schema served by an API server.
func rustRootOf(s *spec.Schema) *rustRoot {
	apiVersion, ok := s.Properties["apiVersion"]
	if !ok {
		return nil
	}
	kind, ok := s.Properties["kind"]
	if !ok {
		return nil
	}

	av, ok := apiVersion.Default.(string)
	if !ok || av == "" {
		return nil
	}
	k, ok := kind.Default.(string)
	if !ok || k == "" {
		return nil
	}

	return &rustRoot{apiVersion: av, kind: k}
}

// rustFieldDoc returns the documentation for a field: its description, plus the
// values a string enum accepts. The values are documented rather than turned
// into a Rust enum on purpose - Kubernetes adds enum values in minor releases,
// and a closed enum would fail to deserialize an observed resource the day the
// server starts using a new one.
func rustFieldDoc(s *spec.Schema) string {
	doc := s.Description

	var values []string
	for _, v := range s.Enum {
		if str, ok := v.(string); ok {
			values = append(values, "`"+str+"`")
		}
	}
	if len(values) == 0 {
		return doc
	}

	if doc != "" {
		doc += "\n\n"
	}

	return doc + "Allowed values: " + strings.Join(values, ", ") + "."
}

// rustEdge is a reference from one component schema to another.
type rustEdge struct {
	from string
	to   string
}

// rustDetectCycles returns the references that close a reference cycle, which
// have to be boxed for the generated types to have a finite size. Only
// references a field holds inline count: a Vec or a BTreeMap is already an
// indirection, so a cycle running through one is not a problem.
//
// The known case is JSONSchemaProps, whose items and not properties reference
// it back through a wrapper schema.
func rustDetectCycles(all map[string]*spec.Schema) map[rustEdge]bool {
	names := slices.Sorted(maps.Keys(all))

	edges := make(map[string][]string, len(all))
	for _, name := range names {
		edges[name] = rustDirectRefs(all[name], all)
	}

	const (
		open = 1
		done = 2
	)

	boxed := make(map[rustEdge]bool)
	state := make(map[string]int, len(all))

	// Every cycle contains at least one edge back to a node the walk is still
	// inside, so boxing those breaks all of them.
	var visit func(string)
	visit = func(name string) {
		state[name] = open
		for _, to := range edges[name] {
			switch state[to] {
			case open:
				boxed[rustEdge{from: name, to: to}] = true
			case done:
			default:
				visit(to)
			}
		}
		state[name] = done
	}

	for _, name := range names {
		if state[name] == 0 {
			visit(name)
		}
	}

	return boxed
}

// rustDirectRefs returns the component schemas a schema holds inline, itself or
// through one of its inline objects.
func rustDirectRefs(s *spec.Schema, all map[string]*spec.Schema) []string {
	found := make(map[string]bool)
	rustCollectDirectRefs(s, all, found, 0)
	return slices.Sorted(maps.Keys(found))
}

func rustCollectDirectRefs(s *spec.Schema, all map[string]*spec.Schema, found map[string]bool, depth int) {
	if s == nil || depth > rustMaxDepth {
		return
	}

	if target := rustDirectRefTarget(s); target != "" {
		if _, ok := all[target]; ok {
			found[target] = true
		}
		return
	}

	// Arrays put their elements behind a Vec, and additionalProperties puts its
	// values behind a BTreeMap. Both are indirections already.
	if s.Type.Contains("array") || len(s.Properties) == 0 {
		return
	}

	for _, name := range slices.Sorted(maps.Keys(s.Properties)) {
		prop := s.Properties[name]
		rustCollectDirectRefs(&prop, all, found, depth+1)
	}
	for i := range s.AllOf {
		rustCollectDirectRefs(&s.AllOf[i], all, found, depth+1)
	}
}

// rustDirectRefTarget returns the component schema a schema references inline,
// whether directly or through a single-element allOf wrapper.
func rustDirectRefTarget(s *spec.Schema) string {
	if target := rustRefTarget(s.Ref.String()); target != "" {
		return target
	}
	if len(s.AllOf) == 1 && rustNoOwnStructure(s) {
		return rustDirectRefTarget(&s.AllOf[0])
	}
	return ""
}

// rustRenderFile renders the types of one file. Everything is emitted fully
// qualified and one attribute per line, because there is no rustfmt in the CLI
// to tidy up after us.
func rustRenderFile(types []rustType) []byte {
	var sb strings.Builder
	sb.WriteString(rustGeneratedHeader + "\n")

	for _, t := range types {
		sb.WriteString("\n")
		switch t.kind {
		case rustAlias:
			rustWriteDoc(&sb, "", t.doc)
			sb.WriteString("pub type " + t.name + " = " + t.alias + ";\n")

		case rustUntagged:
			rustWriteDoc(&sb, "", t.doc)
			sb.WriteString("#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]\n")
			sb.WriteString("#[serde(untagged)]\n")
			sb.WriteString("pub enum " + t.name + " {\n")
			for _, v := range t.variants {
				sb.WriteString("    " + v.name + "(" + v.typ + "),\n")
			}
			sb.WriteString("}\n")

		case rustStruct:
			rustWriteStruct(&sb, t)
		}
	}

	return []byte(sb.String())
}

func rustWriteStruct(sb *strings.Builder, t rustType) {
	rustWriteDoc(sb, "", t.doc)

	// A resource pre-fills its apiVersion and kind in a hand-written Default
	// impl, so it must not derive one. Eq is left out throughout: a schema with
	// a number field maps to f64.
	derives := "#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]\n"
	if t.root != nil {
		derives = "#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]\n"
	}
	sb.WriteString(derives)

	sb.WriteString("pub struct " + t.name + " {\n")
	for i, f := range t.fields {
		if i > 0 {
			sb.WriteString("\n")
		}
		rustWriteDoc(sb, "    ", f.doc)
		if f.flatten {
			sb.WriteString("    #[serde(flatten, default, skip_serializing_if = \"" + rustMapType + "::is_empty\")]\n")
		} else {
			sb.WriteString("    #[serde(rename = " + strconv.Quote(f.jsonName) + ", default, skip_serializing_if = \"Option::is_none\")]\n")
		}
		sb.WriteString("    pub " + f.name + ": " + f.typ + ",\n")
	}
	sb.WriteString("}\n")

	if t.root == nil {
		return
	}

	// The consts and the Default impl are what let a function build a resource
	// without naming its group and version: a model carries its own
	// apiVersion and kind, so no trait shared with an SDK has to stamp them.
	sb.WriteString("\nimpl " + t.name + " {\n")
	sb.WriteString("    /// The apiVersion of this resource.\n")
	sb.WriteString("    pub const API_VERSION: &'static str = " + strconv.Quote(t.root.apiVersion) + ";\n")
	sb.WriteString("\n")
	sb.WriteString("    /// The kind of this resource.\n")
	sb.WriteString("    pub const KIND: &'static str = " + strconv.Quote(t.root.kind) + ";\n")
	sb.WriteString("}\n")

	sb.WriteString("\nimpl Default for " + t.name + " {\n")
	sb.WriteString("    fn default() -> Self {\n")
	sb.WriteString("        Self {\n")
	for _, f := range t.fields {
		switch {
		case f.flatten:
			sb.WriteString("            " + f.name + ": " + rustMapType + "::new(),\n")
		case f.jsonName == "apiVersion":
			sb.WriteString("            " + f.name + ": Some(Self::API_VERSION.to_string()),\n")
		case f.jsonName == "kind":
			sb.WriteString("            " + f.name + ": Some(Self::KIND.to_string()),\n")
		default:
			sb.WriteString("            " + f.name + ": None,\n")
		}
	}
	sb.WriteString("        }\n")
	sb.WriteString("    }\n")
	sb.WriteString("}\n")
}

// rustWriteDoc renders a schema description as doc comments. Descriptions are
// arbitrary prose, so they go in verbatim; the crate root allows the rustdoc
// lints they trip and the manifest turns doctests off.
func rustWriteDoc(sb *strings.Builder, indent, doc string) {
	// A carriage return ends a line, with or without a line feed after it, as
	// it does in the Go models. Rust rejects a bare one in a doc comment.
	doc = strings.ReplaceAll(strings.ReplaceAll(doc, "\r\n", "\n"), "\r", "\n")

	// Descriptions routinely end in a newline, which would leave the comment
	// with a blank line between it and what it documents.
	doc = strings.TrimSpace(doc)
	if doc == "" {
		return
	}

	for line := range strings.SplitSeq(doc, "\n") {
		line = strings.TrimRight(line, " \t")
		if line == "" {
			sb.WriteString(indent + "///\n")
			continue
		}
		sb.WriteString(indent + "/// " + line + "\n")
	}
}

// BuildRustModuleTree rewrites everything about the generated Rust crate rooted
// at crateFS that depends on which models it holds: the module declarations in
// src/lib.rs and in one mod.rs per directory, and the manifest, whose features
// gate those modules.
//
// The schema manager copies the output of every source into one crate, and a
// generator run only ever sees its own source, so none of this can be written
// while emitting. The manager calls this again once it has merged everything,
// the same way it rebuilds the JSON index schema.
func BuildRustModuleTree(crateFS afero.Fs) error {
	ok, err := afero.DirExists(crateFS, rustSrcDir)
	if err != nil {
		return errors.Wrap(err, "failed to stat the generated Rust crate's source directory")
	}
	if !ok {
		return nil
	}

	features, err := rustCollectFeatures(crateFS)
	if err != nil {
		return err
	}

	if err := afero.WriteFile(crateFS, "Cargo.toml", []byte(rustRenderCargoToml(features)), 0o644); err != nil {
		return errors.Wrap(err, "failed to write Cargo.toml")
	}

	return rustBuildModule(crateFS, rustSrcDir, features)
}

func rustBuildModule(crateFS afero.Fs, dir string, features map[string]rustFeature) error {
	entries, err := afero.ReadDir(crateFS, dir)
	if err != nil {
		return errors.Wrapf(err, "failed to read directory %q", dir)
	}

	var modules, files []string
	for _, e := range entries {
		if e.IsDir() {
			modules = append(modules, e.Name())
			continue
		}
		stem, ok := strings.CutSuffix(e.Name(), ".rs")
		if !ok || e.Name() == "mod.rs" || e.Name() == "lib.rs" {
			continue
		}
		files = append(files, stem)
	}
	slices.Sort(modules)
	slices.Sort(files)

	for _, m := range modules {
		if err := rustBuildModule(crateFS, path.Join(dir, m), features); err != nil {
			return err
		}
	}

	root := dir == rustSrcDir

	var sb strings.Builder
	sb.WriteString(rustGeneratedHeader + "\n")
	if root {
		sb.WriteString(rustCrateAttributes)
	}
	if len(modules) > 0 || len(files) > 0 {
		sb.WriteString("\n")
	}
	for _, m := range modules {
		// Gating the module, rather than the types in it, is what lets rustc
		// tell a function that imports from it which feature to enable.
		if f, ok := features[path.Join(dir, m)]; ok {
			sb.WriteString("#[cfg(feature = \"" + f.name + "\")]\n")
		}
		sb.WriteString("pub mod " + m + ";\n")
	}
	if len(modules) > 0 && len(files) > 0 {
		sb.WriteString("\n")
	}
	// Types are re-exported by the module their schema names, so a file name
	// never appears in a use declaration.
	for _, f := range files {
		sb.WriteString("mod " + f + ";\n")
		sb.WriteString("pub use " + f + "::*;\n")
	}

	name := "mod.rs"
	if root {
		name = "lib.rs"
	}

	return afero.WriteFile(crateFS, path.Join(dir, name), []byte(sb.String()), 0o644)
}
